### ISSUE TITLE
Query string params causes error

### ISSUE THREAD

**Issue by dburles** [EventedMind/iron-router#1151]
Passing say `?foo=1&foo[]=1` causes an error

```
TypeError: Object 1 has no method 'push'
    at packages/iron:url/lib/url.js:110:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at Function.Url.fromQueryString (packages/iron:url/lib/url.js:102:1)
    at Function.Url.parse (packages/iron:url/lib/url.js:206:1)
    at Function.Url.normalize (packages/iron:url/lib/url.js:59:1)
    at [object Object].Url.test (packages/iron:url/lib/url.js:247:1)
    at [object Object].Handler.test (packages/iron:middleware-stack/lib/handler.js:90:1)
    at Function.Router.findFirstRoute (packages/iron:router/lib/router.js:160:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:191:1)
```

**Comment by dburles** [comment]
https://github.com/EventedMind/iron-url/pull/6
