### ISSUE TITLE
support for posting text/plain to server routes broken

### ISSUE THREAD

**Issue by dradetsky** [EventedMind/iron-router#1153]
In re #582

This used to work on 0.9.4, but since the 1.0 upgrade, posting text/plain yields "Meteor code must always run within a Fiber." Entire app is below:

```
Router.map(function() {
  this.route('hook_unsubscribe', {
    where: 'server',
    path: '/hooks/unsubscribe',
    action: function() {
      console.log('===>body:', this.request.body);
      this.response.end('ok\n');
    }
  });
});

if (Meteor.isServer) {
  var connectHandlers;

  if (__meteor_bootstrap__ && typeof __meteor_bootstrap__.app !== 'undefined') {
    connectHandlers = __meteor_bootstrap__.app;
  } else {
    connectHandlers = WebApp.connectHandlers;
  }

  connectHandlers.use((function(req, res, next) {
    if (req && req.headers['content-type'] &&
        req.headers['content-type'].indexOf('text/plain') != -1) {
      var bodyarr = [];
      req.on('data', function(chunk) {
        bodyarr.push(chunk);
      });
      req.on('end', function() {
        req.body = bodyarr.join('');
        next();
      });
    }
    else {
      next();
    }
  }));
}
```

Without the custom middleware, there is no error, but the body is an empty object (whether I send good json or not).

Is there a new way to patch the router so it handles text/plain?

**Comment by boustanihani** [comment]
Replace your code by the following:
```javascript
if (Meteor.isServer) {
    Router.onBeforeAction(Iron.Router.bodyParser.text());
}
```

Take a look at:
https://github.com/EventedMind/iron-router/blob/1.0.6/lib/router_server.js#L14

**Comment by theplatapi** [comment]
It's still broken for me when I add this. I see the following error:

```js
Error: No hook found named: undefined
    at Function.Router.lookupHook (packages/iron:router/lib/router.js:306:1)
    at Router.addHook.hookWithOptions (packages/iron:router/lib/router.js:277:1)
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].Router.addHook.hookWithOptions (packages/iron:router/lib/router.js:276:1)
    at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
    at Meteor.bindEnvironment.runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at Meteor.bindEnvironment (packages/meteor/dynamics_nodejs.js:121:1)
    at [object Object].textParser
    at Router.addHook.hookWithOptions (packages/iron:router/lib/router.js:277:1)
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```
I get a similar output for every POST I try, with or without the body parser added.

**Comment by dradetsky** [comment]
The stated solution worked for me. Triple-check for mistakes elsewhere.

**Comment by theplatapi** [comment]
I fixed the issue. I had another Router.onBeforeAction call which messed things up. Removing that and having `Router.onBeforeAction(Iron.Router.bodyParser.text());` as my only call fixed it.

**Comment by patmoore** [comment]
Why isn't this on by default? I wasted hours on this problem. I would expect the raw bytes to always be available no matter what the content type. Lots of servers lie or are "casual" about getting the content type correct.

Debugging those kinds of problems should not be made harder by hiding the actual bytes sent over.

**Comment by ShaunEgan** [comment]
This also solved my problem. Thanks.
