### ISSUE TITLE
Iron router can't take numbers as routes, a single route breaks all routes

### ISSUE THREAD

**Issue by Tarang** [EventedMind/iron-router#1188]
If any route begins with a number, the entire app will break and no routes will be served.

Throws the following error

```
TypeError: Cannot read property 'handler' of undefined
at Function.Router.findFirstRoute (packages/iron:router/lib/router.js:160:1)
at Function.Router.createController (packages/iron:router/lib/router.js:191:1)
at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
at Object.router (packages/iron:router/lib/router.js:15:1)
at next (~/.meteor/packages/webapp/.1.1.5.1jhs14c++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
at Function.app.handle (~/.meteor/packages/webapp/.1.1.5.1jhs14c++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:198:3)
at Object.fn [as handle] (~/.meteor/packages/webapp/.1.1.5.1jhs14c++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:74:14)
at next (~/.meteor/packages/webapp/.1.1.5.1jhs14c++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
at Object.WebAppInternals.staticFilesMiddleware (packages/webapp/webapp_server.js:400:1)
at packages/webapp/webapp_server.js:651:1
```

```
meteor list

autopublish      1.0.2  Publish the entire database to all clients
insecure         1.0.2  Allow all database writes by default
iron:router      1.0.7  Routing specifically designed for Meteor
meteor-platform  1.2.1  Include a standard set of Meteor packages in your app
```

Reproduction:

```
meteor create test
cd test
meteor add iron:router
```

test.js (replace all content with)
```
Router.route('/123', function () {
//anything can go here
});
```

**Comment by newswim** [comment]
Is iron router doing some kind of validation that's refusing to parse a number type?

**Comment by joaopiopedreira** [comment]
+1

**Comment by Charpeni** [comment]
I have the same problem, a fix would be interesting.

**Comment by phocks** [comment]
I just ran into the exact same problem trying to do a /404 route. Not sure what's going on. Does flow router handle number only routes?
